package com.gregory.revelation;

public class FlavorGenerator {

    /*these appear randomly on the game screen as a fun little thing*/
    private static String[] texts = {
            "you exist. congratulations!",
            "truth is, we're all fucked up.",
            "if you hear voices, see a doctor.",
            "life is strange.",
            "adults post the darndest things.",
            "if they make you feel small, lose their number",
            "when it's a tossup, choose to be kind.",
            "hate must never win.",
            "listen to Pink Floyd some time.",
            "don't make people feel bad for liking things.",
            "thank you for playing my little game.",
            "like the game? tell your friends!",
            "what is up with the color red?",
            "rick and morty won an emmy. nice!",
            "take a deep breath and relax.",
            "black is a beautiful color.",
            "i'm not actually sad, it's just my aesthetic.",
            "do you need a brain update?",
            "the world is crazy, and getting crazier.",
            "there are no points in this game.",
            "holy shit, we landed on the moon!",
            "marijuana is slightly psychedelic.",
            "once you get the message, hang up the phone.",
            "probably don't have sex with your roommate!",
            "give someone near you a hug.",
            "there is no replacement for a reading habit.",
            "be creative! make things! you have ideas!",
            "one must imagine sisyphus happy.",
            "if it won't make you proud, don't do it!",
            "every dog is a good dog. no exceptions.",
            "cats probably know something we don't.",
            "appreciate someone? let them know!",
            "vegan men live 25% longer than omnivores",
            "brevity is the soul of wit.",
            "our planet is dying at an alarming rate.",
            "taylor swift is 25 years old",
            "life has a way of fixing itself.",
            "darling, you are definitely real.",
            "i love you.",
            "old school runescape exists. you should play it.",
            "strive for ethical consistency in your life.",
            "try to think for yourself as much as possible.",
            "we are all stardust.",
            "psychedelics are crazy.",
            "become an expert in something.",
            "you've changed... for the better.",
            "a pet is great for your mental health.",
            "happiness is a journey, not a goal.",
            "this game doesn't even use the internet.",
            "water is refreshing.",
            "is water wet or does water get things wet?",
            "immigrants commit less crimes than citizens.",
            "college rules.",
            "always be suspicious of your dentist.",
            "you should not be here. leave.",
            "he screams, for he can do nothing else.",
            "there was never hope in the first place.",
            "don't worry. we forgive you.",
            "begone, thought!",
            "i take cash, credit and debit. never lobster.",
            "pepsi is never okay.",
            "just say no to non-orientable shapes.",
            "why.",
            "i scream into the void. it answers with jazz.",
            "vimeo seems like the hot thing right now.",
            "wanna go out with me?",
            "the moon is nervous again.",
            "hate your gender? try astral projection.",
            "loading...",
            "are you having fun?",
            "it's ok to express yourself sexually.",
            "you can play this game one handed.",
            "this is a low-key game.",
            "does this even qualify as a game?",
            "*internal screaming*",
            "what is going on right now?",
            "help? there is no help.",
            "they're trying to build a prison.",
            "why do they always send the poor?!",
            "blast off! it's party time.",
            "where are you?",
            "still thinking. sorry...",
            "such a lonely day, and it's mine.",
            "what happened on the worst day of your life?",
            "sorry, it's my first time.",
            "tell rebecca that i think she's cute.",
            "i write these when i'm bored.",
            "if i don't make this, i won't make anything.",
            "if you don't laugh, you'll cry.",
            "don't let your dreams be memes.",
            "the word meme predates the internet.",
            "i'm feeding off of your gps data (jk).",
            "alright.",
            "ok."
    };

    public static String grabFlavor(){
        return texts[getRandomIntegerBetweenRange(0, texts.length)];
    }

    public static int getRandomIntegerBetweenRange(int min, int max){
        int x = (int)(Math.random()*((max-min)+1))+min;
        return x;
    }
}
