package com.gregory.revelation;

public class FlavorGenerator {

    //these appear randomly on the game screen as a fun little thing
    //these are not meant to be professional and do not reflect professional behavior
    //TODO: add a separate list for "inappropriate messages" in order to have a disable option
    private static final String[] texts = {
            "you exist. congratulations!",
            "truth is, we're all fucked up.",
            "if you hear voices, see a doctor.",
            "life is strange.",
            "adults post the darndest things.",
            "if they make you feel small, lose their number",
            "when it's a tossup, choose to be kind.",
            "hate must never win.",
            "listen to pink floyd some time.",
            "don't make people feel bad for liking things.",
            "thank you for playing my little game.",
            "like the game? tell your friends!",
            "what is up with the color red?",
            "rick and morty won an emmy. nice!",
            "take a deep breath and relax.",
            "black is a beautiful color.",
            "i'm not actually sad, it's just my aesthetic.",
            "do you need a brain update?",
            "the world is crazy, and getting crazier.",
            "there are no points in this game.",
            "holy shit, we landed on the moon!",
            "once you get the message, hang up the phone.",
            "give someone near you a hug.",
            "there is no replacement for a reading habit.",
            "be creative! make things! you have ideas!",
            "one must imagine sisyphus happy.",
            "if it won't make you proud, don't do it!",
            "every dog is a good dog. no exceptions.",
            "cats probably know something we don't.",
            "appreciate someone? let them know!",
            "vegan men live 25% longer than omnivores",
            "brevity is the soul of wit.",
            "our planet is dying at an alarming rate.",
            "taylor swift is 25 years old",
            "life has a way of fixing itself.",
            "darling, you are definitely real.",
            "i love you.",
            "old school runescape: you should play it.",
            "find ethical inconsistencies in your life.",
            "think for yourself as much as possible.",
            "we are all stardust.",
            "become an expert in something.",
            "you've changed... for the better.",
            "a pet is great for your mental health.",
            "happiness is a journey, not a goal.",
            "this game doesn't even use the internet.",
            "water is, by definition, refreshing.",
            "is water wet or does water get things wet?",
            "immigrants commit less crimes than citizens.",
            "college rules.",
            "always be suspicious of your dentist.",
            "you should not be here. leave.",
            "he screams, for he can do nothing else.",
            "there was never hope in the first place.",
            "don't worry. we forgive you.",
            "begone, thought!",
            "i take cash, credit and debit. never lobster.",
            "pepsi is never okay.",
            "just say no to non-orientable shapes.",
            "why.",
            "i scream into the void. it answers with jazz.",
            "vimeo seems like the hot thing right now.",
            "wanna go out with me?",
            "the moon is nervous again.",
            "hate your gender? try astral projection.",
            "loading...",
            "are you having fun?",
            "it's ok to express yourself sexually.",
            "you can play this game one handed.",
            "this is a low-key game.",
            "does this even qualify as a game?",
            "*internal screaming*",
            "what is going on right now?",
            "help? there is no help.",
            "they're trying to build a prison.",
            "why do they always send the poor?!",
            "blast off! it's party time.",
            "where are you?",
            "still thinking. sorry...",
            "such a lonely day, and it's mine.",
            "what happened on the worst day of your life?",
            "sorry, it's my first time.",
            "tell rebecca that i think she's cute.",
            "i write these when i'm bored.",
            "if i don't make this, i won't make anything.",
            "if you don't laugh, you'll cry.",
            "don't let your dreams be memes.",
            "don't let your memes be dreams",
            "the word meme predates the internet.",
            "i'm feeding off of your gps data (jk).",
            "alright.",
            "ok.",
            "be careful of the milkman.",
            "i am the milkman. my milk is amazing.",
            "do not fear death. you've got to go some time.",
            "guacamole is definitely pretty extra.",
            "now introducing: fried coke.",
            "if i had any more beefs with you, it'd be a farm",
            "now introducing: red lemons.",
            "now introducing: purple oranges.",
            "please don't do coke in my bathroom",
            "searching for cell signal...",
            "hey there delilah.",
            "what makes you think a man made this?",
            "failed to add friend. she is too far away.",
            "sorry, come again?",
            "have you ever kissed a spider?",
            "she was beautiful. her smile was radiant.",
            "shelby put the 4 in 416",
            "if you have ugly thoughts, see a counselor.",
            "are you feeling it now?",
            "this game is about relaxing with your friends.",
            "have you ever tasted the color yellow?",
            "kink shaming is bad. don't do it.",
            "be excellent to each other.",
            "man gets self in hole. gets out again. classic.",
            "oh, how... how i wish you were here.",
            "i wonder if anyone will ever play this game.",
            "it would be embarrassing if this got popular.",
            "wow, what just happened?",
            "are you up or down?",
            "this isn't even my final form.",
            "before you touch anyone anywhere: ask.",
            "consent is not just sexy: it's required.",
            "drugs are fun, but terrible for productivity.",
            "bad decisions will always catch up to you.",
            "the world is one big, very kinky orgy.",
            "what do you want from me?",
            "should you stay or should you go?",
            "better luck next time.",
            "this game has no advertising budget!",
            "the things you want won't magically happen.",
            "hello. hello. is this thing on? hello.",
            "do you think you can tell?",
            "you are already dead.",
            "no, seriously: what?",
            "marijuana is slightly psychedelic.",
            "probably don't have sex with your roommate!",
            "psychedelics are crazy.",
            "not just you: everyone has a hot cousin.",
            "this game is on my resume.",
            "this game is not for serious.",
            "initiating self-destruct sequence now.",
            "wow. just wow.",
            "butt stuff is a terrible surprise.",
            "transmission received",
            "when was the last time you felt real fear?",
            "i have become so uncomfortably numb.",
            "when was the last time you cried?",
            "if it ain't a sexy booty, i don't want it.",
            "i forgot what i was going to say.",
            "are you okay?",
            "the universe... what a concept.",
            "eric killed the video star.",
            "no such thing as a stupid question.",
            "strong messages land on few ears.",
            "self-policing is the best policing.",
            "bitch, stay humble.",
            "emotions are an engine, not a burden.",
            "delete everything.",
            "heavy music is the best music.",
            "i curse not the wicked, praise not the blessed.",
            "lady luck is a fickle mistress.",
            "learn about your prostate gland today!",
            "most people are just trying their best.",
            "strangers doing strange things: totally normal.",
            "stop wondering. just ask.",
            "look people in the eyes. listen to their eyeballs.",
            "getting stoned: fun. sometimes, deadly.",
            "try not to run away from yourself.",
            "you break it, you buy it. except for hearts.",
            "i made this!"
    };

    //at some point, this game will supply questions to start the game off
    private static final String[] startingQuestions = {
            "favorite meme?",
            "favorite memory?",
            "what do you eat way too much of?",
            "what are your biggest pet peeves?",
            "most embarrassing memory?",
            "hardest lesson learned?",
            "how do you feel about social media?",
            "is money really the root of all evil?",
            "when was the last time you were violent, if ever?",
            "do you have any regrets?",
            "what is your idea of perfect happiness?",
            "what is your greatest fear?",
            "when was the last time you felt real fear?",
            "what traits do you most like/dislike in yourself?",
            "what is your greatest extravagance?",
            "what is your current state of mind?",
            "what do you consider the most overrated virtue?",
            "on what occasion do you lie?",
            "what do you most like/dislike about your appearance?",
            "which living person do you most despise?",
            "what is the quality you most like in a man? a woman?",
            "which words or phrases do you most overuse?",
            "what is the greatest love of your life?",
            "when and where were you happiest?",
            "which talent would you most like to have?",
            "if you could change one thing about yourself, what would it be?",
            "what do you consider your greatest achievement?",
            "if you were to die and come back as a person or a thing, what would it be?",
            "where would you most like to live?",
            "what is your most treasured possession?",
            "what is your favorite way to kill time alone?",
            "what is your most marked characteristic?",
            "what do you most value in your friends?",
            "who are your favorite writers, if any?",
            "who is your hero of fiction?",
            "which historical figure do you most identify with?",
            "hwo are your heroes in real life?",
            "what are your favorite names?",
            "what is it that you most dislike?",
            "what is your greatest regret?",
            "how would you like to die?",
            "do you fear death?",
            "what is your motto?",
            "do you like watching reruns?",
            "have you ever won any kind of contest?",
            "what gives you cheap thrills?",
            "what do you think is worth waiting for?",
            "are you an organ donor, if so why/why not?",
            "should parenting classes be mandatory for new parents?",
            "what is the number one thing people are always asking you for help with?",
            "what movie did you love the original but hate the sequel?",
            "are you more talk and less action or vice versa?",
            "have you ever given someone a handmade present?",
            "have you ever been given a handmade present?",
            "what type of person angers you the most?",
            "what would you do without electric for a week?",
            "have you ever eaten a whole tube of pringles by yourself?",
            "do you like champagne? if so: favorite brand?",
            "what nervous habits do you have?",
            "what do you do when tou and your best friend get into a fight?",
            "what comforts you on bad days?",
            "do you treat yourself and your body with respect?",
            "something you eat that other people would find gross?",
            "have you ever broken the law and didn't get caught, if so how?",
            "something you fear might change you.",
            "what personality traits raise red flags?",
            "have you ever resented someone, if so what for?",
            "do you have a favorite t-shirt? what is it?",
            "how old do you think is too old to have a baby?",
            "would you ever consider adopting a child?",
            "how have you changed over the last 5 years?",
            "what makes you feel miserable?",
            "what's the best costume you've ever worn?",
            "what's been the hardest loss you've had to take?",
            "do you prefer sun or rain?",
            "what does your typical Friday night look like?",
            "who is your favorite movie director and what's your favorite movie from them?",
            "what is the furthest you've ever got a paper airplane to fly?",
            "could you do something as a kid that you can't do anymore?",
            "do you like the person you're becoming?",
            "what's the highest you've ever jumped into the water from?",
            "what inspires you?",
            "have you ever assembled furniture by yourself?",
            "most painful thing you've ever had to throw out?",
            "what is the biggest letdown you've ever experienced?",
            "how emotional are you?",
            "do you prefer chicken, beef, seafood, or plants?",
            "have you ever had a health scare?",
            "what do you love most about the holidays?",
            "do you think a fling could be a good thing?",
            "what part of your routine do you always try to skip if you can?",
            "what do or did you hate most about dating or the dating process?",
            "when was the last time you personally noticed and fixed a problem?",
            "what do you frown upon when it comes to raising kids?",
            "have you ever been professionally photographed?",
            "where or how do you find serenity?",
            "do you sleep well?",
            "do you influence people more than they influence you?",
            "what is your favorite hiding place?",
            "do you buy anything organic? if so: what?",
            "describe your cuisine.",
            "how could you reinvent yourself?",
            "what is the name of the first album you ever bought and who was it by?",
            "who is the very first friend you ever remember making and how old were you?",
            "what makes you lose sleep?",
            "what are 3 phrases or saying you say almost every day?",
            "have you ever felt genuinely uncomfortable?",
            "what is the most dangerous thing you've ever done?",
            "what do you personally consider to be an artistic masterpiece?",
            "when was the last time you had your mind blown? why?",
            "what has gotten worse over time? what has gotten better?",
            "what has made you pause and think 'i am definitely getting older.'?",
            "are you easily impressed?",
            "what is the best money you've ever spent?",
            "what is the worst money you've ever spent?",
            "has a celebrity death ever affected you emotionally?"
    };

    public static String grabFlavor(){
        return texts[Util.getRandomIntegerBetweenRange(0, texts.length-1)];
    }

    public static String grabQuestion(){
        return startingQuestions[Util.getRandomIntegerBetweenRange(0, startingQuestions.length-1)];
    }
}
